-intstyle "ise" -incremental -lib "unisims_ver" -lib "unimacro_ver" -lib "xilinxcorelib_ver" -lib "secureip" -o "D:/five/fiveTB_isim_beh.exe" -prj "D:/five/fiveTB_beh.prj" "work.fiveTB" "work.glbl" 
